### ISSUE TITLE
Can't connect to host.

### ISSUE THREAD

**Issue by TheRickson** [fp12/achallonge#1]
I tried making a bot for Discord using your library. Though when i did everything that was mentioned here I just get [Errno 101] Cannot connect to host api.challonge.com:443 ssl:True [Can not connect to api.challonge.com:443 [Network is unreachable]]. Any ideas on what's wrong?

**Comment by fp12** [comment]
Can you paste some of the code you have (without credentials)?
Thanks!

**Comment by TheRickson** [comment]
```python
import discord
from discord.ext import commands
from .utils import checks
from .utils.dataIO import dataIO
from __main__ import send_cmd_help, settings
from collections import deque, defaultdict
import aiohttp
import asyncio
import os
import re
import challonge

class challonger:
    """Cog for challonge.com"""
    def __init__(self, bot):
        self.bot = bot

    @commands.group(pass_context=True)
    async def challonger(self, ctx):
        """Main challonger command"""

        if ctx.invoked_subcommand is None:
            await send_cmd_help(ctx)

    @challonger.command(pass_context=True)
    async def tt(self, ctx):

        user = await challonge.get_user('username', 'apikey')
        tournament = await user.get_tournaments()
        for t in tournament:
        	await self.bot.say(t.id + t.name + t.status)

def setup(bot):
    bot.add_cog(challonger(bot))
```

That's my whole code. I hope you will find my mistake :P

**Comment by fp12** [comment]
Your code seems good.
And since the error seems to be network related so can you try reaching `https://username:api-key@api.challonge.com/v1/tournaments.json` in a browser?
Let me know how it goes!

**Comment by TheRickson** [comment]
I just get the .json file. All the data, but when i try it with code i'm still getting the error :/

**Comment by fp12** [comment]
That's weird. I just ran the unit tests and they are working right now. 
There might be something off with you network environment but I don't know what. 
Can you try running your code from somewhere else (another machine / another network / cloud services like heroku...) ?

**Comment by TheRickson** [comment]
Okay, it appears that the problem is on my end. Don't know why though. It appears I can't connect with any api's. Not sure why, will try and ressolve this :) Thanks for help ;)

**Comment by fp12** [comment]
My pleasure! Let me know how it goes once you got it working.
By the way, we can further discuss on discord on this server: https://discord.gg/KSRxBav
Cheers!
